server:
  port: 8765

spring:
  application:
    name: hr-api-gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**

    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**

    user:
      service-id: hr-user
      path: /hr-user/**

    oauth:
      service-id: hr-oauth
      path: /hr-oauth/**
      sensitiveHeaders:
        - Cookie
        - Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  connectTimeout: 10000
  readTimeout: 20000
